version: '3'
services:
  db:
    container_name: db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'mysql'
      MYSQL_DATABASE: E_commerce2
    ports:
      - '3307:3306'
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - e-commerce_default
  second-springboot-app:
    image: mouradtals/secondecommerce:0.0.1
    depends_on:
      - db
    build: .
    ports:
      - "8082:8082"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: 'mysql'
      MYSQL_PORT: 3306
      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:29092
    networks:
        - e-commerce_default

networks:
  e-commerce_default:
    external: true


