version: '3'
services:
  db:
    container_name: db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: E_commerce2
    ports:
      - '3361:3306'
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - ecommerceboukri_default
  second-springboot-app:
    image: mouradtals/secondecommerce:0.0.1-SNAPSHOT
    depends_on:
      - db
    ports:
      - "8082:8082"
    build: .
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: mysql

      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:29092
    networks:
        - ecommerceboukri_default

networks:
  ecommerceboukri_default:
    external: true


